### ISSUE TITLE
!! Error evaluating 'gcode_macro NOZZLE_PRIME_LINE:gcode': UndefinedError: 'dict object' has no attribute 'firmware_retraction'

### ISSUE THREAD

**Issue by mjschipper** [dudeofawesome/klipper-config#2]
Hi,

I'm shifting to klipper fr my ender 3 max and found your repo. Everything looks great but when i add the print_start gcode to superslicer by deleting everything and just adding your  "START_PRINT HOTEND......" line to the start g-code area, slice and attempt to print i get this error.

"!! Error evaluating 'gcode_macro NOZZLE_PRIME_LINE:gcode': UndefinedError: 'dict object' has no attribute 'firmware_retraction'".

Have you seen this previously? I cant see a reference to firmware_retraction anywhere.

Thanks again.

**Comment by dudeofawesome** [comment]
Yeah, you need to enable firmware retraction in your Klipper config.

**Comment by vmincev** [comment]
> Yeah, you need to enable firmware retraction in your Klipper config.

Can you please provide example of firmware_retraction? Will it override Slicer retraction?

**Comment by dudeofawesome** [comment]
[Here's the settings in my config](https://github.com/dudeofawesome/klipper-config/blob/master/skr-mini-e3-v1.2.cfg#L126-L128), and [here's the Klipper docs for it](https://www.klipper3d.org/Config_Reference.html?h=firmware#firmware_retraction)

Edit: No, adding the firmware retraction setting to your config will not force your slicer to use firmware retraction.

**Comment by mjschipper** [comment]
Great. Got it working, not sure how i missed that. Thanks again. :)
